import {useEffect,useRef,useState} from "react";
import {Plus,ArrowClockwise,FloppyDisk,ArrowRight} from "@phosphor-icons/react";
import {isLeader} from "./access.jsx";
const labels={available:"В наличии",reserved:"В резерве",sold:"Выдано",archived:"В архиве"};
const money=value=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB"}).format(value);
const fresh=()=>({name:"",vin:"",price:"0",location:"",note:"",requestId:crypto.randomUUID()});
export function Inventory({api,member,onDirtyChange,onOpen,initialId}){
  const [q,setQ]=useState(""),[status,setStatus]=useState("available"),[page,setPage]=useState(0),[revision,setRevision]=useState(0);
  const [data,setData]=useState({items:[],hasMore:false}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState(initialId || null);
  const dirty=useRef(false);
  useEffect(()=>{
    let active=true;setLoading(true);
    const timer=setTimeout(()=>api(`/inventory?${new URLSearchParams({q,status,offset:String(page*30)})}`).then(result=>{if(active){setData(result);setError("");}}).catch(failure=>{if(active){setData({items:[],hasMore:false});setError(failure.message);}}).finally(()=>{if(active)setLoading(false);}),150);
    return()=>{active=false;clearTimeout(timer);};
  },[api,q,status,page,revision]);
  const select=id=>{if(dirty.current && !window.confirm("Отменить несохранённые изменения техники?"))return;setSelected(id);};
  return <section className="screen"><div className="page-heading"><h1>Шоурум и склад</h1>{isLeader(member) && <button className="primary-button" onClick={()=>select("new")}><Plus size={18}/>Добавить технику</button>}</div>
    <div className="inventory-filters"><input aria-label="Поиск техники" placeholder="Модель, VIN, место хранения" value={q} onChange={event=>{setQ(event.target.value);setPage(0);}}/><select aria-label="Наличие техники" value={status} onChange={event=>{setStatus(event.target.value);setPage(0);}}><option value="">Все</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button className="icon-button" title="Обновить склад" aria-label="Обновить склад" onClick={()=>setRevision(value=>value+1)}><ArrowClockwise size={18}/></button></div>
    {error && <p role="alert">{error}</p>}{loading && <p role="status">Загрузка склада…</p>}
    <div className="sales-layout"><div className="sales-register">{!loading && !error && !data.items.length && <p className="empty-state">Техника не найдена</p>}{data.items.map(item=><button className={`sales-row ${selected===item.id?"active":""}`} disabled={loading} key={item.id} onClick={()=>select(item.id)}><strong>{item.name}</strong><span>{labels[item.status]} · {money(item.price)}</span><small>{item.vin || "Без VIN"} · {item.location}</small></button>)}<div className="button-row"><button className="ghost-button" disabled={loading || page===0} onClick={()=>setPage(value=>value-1)}>Назад</button><span>{page+1}</span><button className="ghost-button" disabled={loading || !data.hasMore} onClick={()=>setPage(value=>value+1)}>Далее</button></div></div>
      <div className="sales-detail">{selected?<InventoryEditor key={selected} id={selected} api={api} member={member} onOpen={onOpen} onDirtyChange={value=>{dirty.current=value;onDirtyChange(value);}} onSaved={item=>{setSelected(item.id);setRevision(value=>value+1);}}/>:<p className="empty-state">Выберите технику</p>}</div></div>
  </section>;
}
function InventoryEditor({id,api,member,onDirtyChange,onSaved,onOpen}){
  const [record,setRecord]=useState(null),[draft,setDraft]=useState(id==="new"?fresh:null),[original,setOriginal]=useState(null);
  const [loading,setLoading]=useState(id!=="new"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0);
  const [dealQuery,setDealQuery]=useState(""),[deals,setDeals]=useState([]),[dealId,setDealId]=useState(""),[dealError,setDealError]=useState("");
  const flight=useRef(false),callback=useRef(onDirtyChange);callback.current=onDirtyChange;
  const dirty=!!draft && (id==="new"?!!(draft.name || draft.vin || draft.location || draft.note || Number(draft.price)):JSON.stringify(draft)!==JSON.stringify(original));
  useEffect(()=>{callback.current(dirty || busy || !!dealId);return()=>callback.current(false);},[dirty,busy,dealId]);
  useEffect(()=>{if(!dirty && !dealId && !busy)return;const handler=event=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty,dealId,busy]);
  const accept=item=>{setRecord(item);const fields={name:item.name,vin:item.vin,price:item.price,location:item.location,note:item.note,version:item.version};setDraft(fields);setOriginal(fields);setDealId("");};
  useEffect(()=>{if(id==="new")return;let active=true;setLoading(true);api(`/inventory/${id}`).then(item=>{if(active){accept(item);setError("");}}).catch(failure=>{if(active)setError(failure.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[api,id,revision]);
  useEffect(()=>{if(record?.status!=="available")return;let active=true;setDeals([]);setDealError("");const timer=setTimeout(()=>api(`/deals?status=open&q=${encodeURIComponent(dealQuery)}`).then(result=>{if(active)setDeals(result.items.filter(item=>isLeader(member) || item.assigneeId===member.id));}).catch(failure=>{if(active)setDealError(failure.message);}),150);return()=>{active=false;clearTimeout(timer);};},[api,record?.status,dealQuery,member.id,member.role,revision]);
  const run=async(path,payload)=>{if(flight.current)return;flight.current=true;setBusy(true);setError("");try{const result=await api(path,payload);accept(result);onSaved(result);}catch(failure){setError(failure.message);}finally{flight.current=false;setBusy(false);}};
  const action=name=>run(`/inventory/${id}/${name}`,{version:record.version,dealId});
  const canManageReservation=isLeader(member) || record?.deal_assignee_id===member.id;
  return <><div className="inventory-head"><h2>{record?.name || "Новая техника"}</h2>{id!=="new" && <button className="icon-button" aria-label="Обновить технику" title="Обновить технику" disabled={busy} onClick={()=>{if(!(dirty || dealId) || window.confirm("Загрузить сохранённую карточку и отменить изменения?"))setRevision(value=>value+1);}}><ArrowClockwise size={18}/></button>}</div>
    {error && <p role="alert">{error}</p>}{loading && <p role="status">Загрузка техники…</p>}
    {draft && !loading && <><p>{record && labels[record.status]}</p><form onSubmit={event=>{event.preventDefault();run(id==="new"?"/inventory":`/inventory/${id}`,draft);}}><fieldset className="client-fields" disabled={busy || !isLeader(member) || (record && record.status!=="available")}><div className="form-grid">{[["name","Модель техники"],["vin","VIN техники"],["price","Стоимость техники"],["location","Место хранения"],["note","Примечание к технике"]].map(([key,label])=><label className="editable-field" key={key}><span>{label}</span><input aria-label={label} required={key==="name" || key==="price"} type={key==="price"?"number":"text"} min={key==="price"?"0":undefined} step={key==="price"?"0.01":undefined} maxLength={key==="vin"?17:key==="note"?2000:200} value={draft[key]} onChange={event=>setDraft(value=>({...value,[key]:event.target.value}))}/></label>)}</div></fieldset>
    {isLeader(member) && (!record || record.status==="available") && <div className="button-row"><button className="primary-button" disabled={busy || (!dirty && id!=="new")}><FloppyDisk size={18}/>Сохранить технику</button>{record && <button type="button" className="ghost-button" disabled={busy || !dirty} onClick={()=>setDraft(original)}>Отменить изменения техники</button>}</div>}</form>
    {record?.deal_id && <p><button className="ghost-button" onClick={()=>onOpen("deals",record.deal_id)}>{record.deal_id} · {record.client}<ArrowRight size={16}/></button></p>}
    {record?.status==="available" && <section className="form-section"><h3>Резерв под сделку</h3>{dealError && <p role="alert">{dealError}</p>}<div className="form-grid"><label className="editable-field"><span>Поиск открытой сделки</span><input aria-label="Поиск сделки для резерва" value={dealQuery} onChange={event=>{setDealQuery(event.target.value);setDealId("");}}/></label><label className="editable-field"><span>Сделка для резерва</span><select aria-label="Сделка для резерва" value={dealId} disabled={busy || dirty} onChange={event=>setDealId(event.target.value)}><option value="">Выберите сделку</option>{deals.map(deal=><option value={deal.id} key={deal.id}>{deal.id} · {deal.client} · {deal.product}</option>)}</select></label></div><button className="primary-button" disabled={busy || dirty || !dealId} onClick={()=>action("reserve")}>Зарезервировать</button></section>}
    {record && <div className="button-row inventory-actions">{record.status==="reserved" && canManageReservation && <><button className="secondary-button" disabled={busy} onClick={()=>{if(window.confirm("Снять резерв техники?"))action("release");}}>Снять резерв</button><button className="primary-button" disabled={busy} onClick={()=>{if(window.confirm("Подтвердить выдачу техники по успешно закрытой сделке?"))action("deliver");}}>Выдать технику</button></>}{isLeader(member) && ["available","archived"].includes(record.status) && <button className="ghost-button" disabled={busy || dirty || !!dealId} onClick={()=>action(record.status==="available"?"archive":"restore")}>{record.status==="available"?"В архив":"Вернуть на склад"}</button>}</div>}
    {record?.events?.length>0 && <section className="form-section"><h3>История техники</h3>{record.events.map(event=><div className="sales-event" key={event.id}><strong>{event.action}</strong><small>{event.actor} · {new Date(event.created_at).toLocaleString("ru-RU")}</small></div>)}</section>}</>}
  </>;
}
export function DealInventory({api,dealId,onOpen}){
  const [data,setData]=useState(null),[error,setError]=useState(""),[revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;api(`/inventory?dealId=${encodeURIComponent(dealId)}`).then(result=>{if(active){setData(result);setError("");}}).catch(failure=>{if(active)setError(failure.message);});return()=>{active=false;};},[api,dealId,revision]);
  return <section className="form-section"><div className="section-title"><h3>Техника со склада</h3><button className="icon-button" title="Обновить резерв" aria-label="Обновить резерв" onClick={()=>setRevision(value=>value+1)}><ArrowClockwise size={18}/></button></div>{error && <p role="alert">{error}</p>}{data?.items.map(item=><button className="linked-sale" key={item.id} onClick={()=>onOpen("inventory",item.id)}><strong>{item.name}</strong><span>{labels[item.status]} · {item.vin || "Без VIN"}</span></button>)}{data && !data.items.length && <p className="empty-state">Техника не закреплена</p>}</section>;
}
